// Objective-C API for talking to github.com/airdeploy/flagger-sdks/wrap/mobile/ios/FlaggerGoWrapper Go package.
//   gobind -lang=objc github.com/airdeploy/flagger-sdks/wrap/mobile/ios/FlaggerGoWrapper
//
// File is generated by gobind. Do not edit.

#ifndef __FlaggerGoWrapper_H__
#define __FlaggerGoWrapper_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperFlagGetPayload(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperFlagGetVariation(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperFlagIsEnabled(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperFlagIsSampled(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperInit(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperPublish(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperSetEntity(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperShutdown(NSString* _Nullable buf);

FOUNDATION_EXPORT NSString* _Nonnull FlaggerGoWrapperTrack(NSString* _Nullable buf);

#endif
