
// Objective-C API for talking to the following Go packages
//
//	github.com/airdeploy/flagger-sdks/wrap/mobile/ios/FlaggerGoWrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FlaggerGoWrapper_FRAMEWORK_H__
#define __FlaggerGoWrapper_FRAMEWORK_H__

#include "FlaggerGoWrapper.objc.h"
#include "Universe.objc.h"

#endif
